export const Users = [
    {
        id: 1,
        profilePicture: "assets/sasuke.jpg",
        username: "Sasuke Uchiha",
        status: "offline",
    },
    {
        id: 2,
        profilePicture: "assets/cow.png",
        username: "cow animal",
        status: "online",
    },
    {
        id: 3,
        profilePicture: "assets/leaf.jpg",
        username: "leaf plant",
        status: "online",
    },
    {
        id: 4,
        profilePicture: "assets/narutojiraiya .jpg",
        username: "naruto jiraiya",
        status: "online",
    },
    {
        id: 5,
        profilePicture: "assets/car.jpeg",
        username: "car machine",
        status: "online",
    },
    {
        id: 6,
        profilePicture: "assets/sasuke.jpg",
        username: "2Sasuke Uchiha",
        status: "online",
    },
    {
        id: 7,
        profilePicture: "assets/cow.png",
        username: "2cow animal",
        status: "online",
    },
    {
        id: 8,
        profilePicture: "assets/leaf.jpg",
        username: "2leaf plant",
        status: "online",
    },
    {
        id: 9,
        profilePicture: "assets/study.jpg",
        username: "nice bench",
        status: "offline",
    },
    {
        id: 10,
        profilePicture: "assets/car.jpeg",
        username: "2car machine",
        status: "online",
    },
    {
        id: 11,
        profilePicture: "assets/sasuke.jpg",
        username: "3Sasuke Uchiha",
        status: "online",
    },
    {
        id: 12,
        profilePicture: "assets/cow.png",
        username: "3cow animal",
        status: "offline",
    },
    {
        id: 13,
        profilePicture: "assets/leaf.jpg",
        username: "3leaf plant",
        status: "online",
    },
    {
        id: 14,
        profilePicture: "assets/study.jpg",
        username: "study boy",
        status: "offline",
    },
    {
        id: 15,
        profilePicture: "assets/car.jpeg",
        username: "3car machine",
        status: "online",
    },
]


export const Posts = [
    {
        id: 1,
        desc: "high above the timony top",
        photo: "assets/festival.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "what a wonderful world",
        photo: "assets/loficat.jpg",
        date: "5 mins ago",
        userId: 2,
        like: 22,
        comment: 3,
    },
    {
        id: 3,
        desc: "what a wonderful world",
        photo: "assets/lotr.jpg",
        date: "5 mins ago",
        userId: 4,
        like: 3,
        comment: 1,
    },
    {
        id: 4,
        desc: "what a wonderful world",
        photo: "assets/pinkart.jpg",
        date: "5 mins ago",
        userId: 7,
        like: 42,
        comment: 12,
    },
    {
        id: 5,
        photo: "assets/pinkmoon.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 42,
        comment: 4,
    },
    {
        id: 6,
        desc: "what a wonderful world",
        photo: "assets/route.jpg",
        date: "5 mins ago",
        userId: 2,
        like: 122,
        comment: 45,
    },
    {
        id: 7,
        photo: "assets/study.jpg",
        date: "5 mins ago",
        userId: 3,
        like: 12,
        comment: 9,
    },
    {
        id: 8,
        desc: "blue birds fly",
        photo: "assets/treemoon.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 12,
        comment: 12,
    },

]